#cloud-config
merge_how:
 - name: list
   settings: [append]
 - name: dict
   settings: [no_replace, recurse_list]
final_message: 'MAAS Installed in $UPTIME'
manage_etc_hosts: false
prefer_fqdn_over_hostname: true
fqdn: maas.ubuntu-show.me
hostname: maas
timezone: America/Los_Angeles
locale: en_US.UTF-8
package_upgrade: true
packages: [git, jq, landscape-client, lynx, ntpdate, petname, postgresql, postgresql-client, postgresql-common, ssl-cert, tree, unzip]
apt:
  conf: |
    APT {
      Get {
        Assume-Yes "true";
        Fix-Broken "true";
        Auto-Remove "true";
        Purge "true";
      };
      Acquire {
        ForceIPv4 "true";
        Check-Date "false";
      };
    };
  primary:
    - arches: [amd64]
      uri: 'http://us-west-1.ec2.archive.ubuntu.com/ubuntu'
      search: ['http://us-west-1.ec2.archive.ubuntu.com/ubuntu', 'http://us-west-2.ec2.archive.ubuntu.com/ubuntu']
  security:
    - arches: [amd64]
      uri: 'http://us-west-1.ec2.archive.ubuntu.com/ubuntu'
      search: ['http://us-west-1.ec2.archive.ubuntu.com/ubuntu', 'http://us-west-2.ec2.archive.ubuntu.com/ubuntu']
  sources_list: |
    deb [arch=amd64] $PRIMARY $RELEASE main universe restricted multiverse
    deb [arch=amd64] $PRIMARY $RELEASE-updates main universe restricted multiverse
    deb [arch=amd64] $SECURITY $RELEASE-security main universe restricted multiverse
    deb [arch=amd64] $PRIMARY $RELEASE-backports main universe restricted multiverse
  sources:
    maas-ubuntu-3_2-focal.list:
      source: 'deb [arch=amd64] https://ppa.launchpadcontent.net/maas/3.2/ubuntu focal main'
      keyid: 3AB6DCF1F234E78DAA9C104204E7FDC5684D4A1C
ssh_pwauth: true
bootcmd:
  - ['cloud-init-per', 'once', 'net0', 'echo', 'network: {config: disabled}', '>', '/etc/cloud/cloud.cfg.d/99-disable-network-config.cfg']
  - |-
    cat <<-NETPLAN|sed -r 's/[ \t]+$//g'|tee 1>/dev/null /etc/netplan/50-cloud-init.yaml
    network:
      version: 2
      renderer: networkd
      ethernets:
        ens5:
          dhcp4: false
          dhcp6: false
          optional: false
          accept-ra: false
          link-local: [ ]
          match:
            macaddress: '$(ip -o l show dev ens5|grep -oP "(?<=ether )[^ ]+")'
          set-name: ens5
      bridges:
        br0:
          macaddress: '$(ip -o l show dev ens5|grep -oP "(?<=ether )[^ ]+")'
          interfaces: ['ens5']
          link-local: [ ]
          dhcp4: true
          dhcp4-overrides:
            use-dns: false
            use-hostname: false
            use-domains: false
            route-metric: 1
          dhcp6: false
          optional: false
          accept-ra: false
          link-local: [ ]
          nameservers:
            addresses: [9.9.9.9,1.1.1.1]
            search: [ubuntu-show.me]
          parameters:
            priority: 0
            stp: false
    NETPLAN
  - ['cloud-init-per', 'once', 'net2', 'netplan', '--debug', 'generate']
  - ['cloud-init-per', 'once', 'net3', 'netplan', '--debug', 'apply']
  - ['cloud-init-per', 'once', 'net3', 'systemctl', 'restart', 'systemd-networkd', 'systemd-resolved', 'procps.service']
  - ['cloud-init-per', 'once', 'bc0', 'set', '-x']
  - ['cloud-init-per', 'once', 'bc1', 'export', 'DEBIAN_FRONTEND=noninteractive']
  - ['cloud-init-per', 'once', 'apt0', 'apt-get', 'update']
  - ['cloud-init-per', 'once', 'apt1', 'apt-get', 'upgrade', 'ubuntu-advantage-tools', '--option=Acquire::ForceIPv4=true', '--assume-yes', '--quiet', '--auto-remove', '--purge']
runcmd:
  - set -x
  - export DEBIAN_FRONTEND=noninteractive
  - apt update
  - export SHOW_ME_ARCH='amd64' SHOW_ME_APP='maas' SHOW_ME_SUBSTRT='aws'
  - mkdir -p /etc/show-me/www /etc/show-me/log
  - "echo 'precedence ::ffff:0:0/96  100'|tee 1>/dev/null -a /etc/gai.conf"
  - export DEFAULT_IP=$(ip -o -4 a show $(ip -o r l default|grep -vE '10\.10\.1[0-9]\.'|grep -m1 -oP "(?<=dev )[^ ]+")|grep -m1 -oP "(?<=inet )[^/]+")
  - sed -i -r "s/127.0.1.1/$DEFAULT_IP/;/127.*localhost/a ${DEFAULT_IP}\t$(hostname -f) $(hostname -s)" /etc/hosts
  - systemctl restart systemd-networkd systemd-resolved procps.service
  - git clone https://github.com/ThinGuy/show-me.git /opt/show-me
  - git clone https://github.com/canonical/packer-maas /opt/show-me/packer-maas
  - curl -fSlL -o /opt/show-me/packer_1.8.0_linux_amd64.zip "https://releases.hashicorp.com/packer/1.8.0/packer_1.8.0_linux_${SHOW_ME_ARCH}.zip"
  - if [ -f /opt/show-me/packer_1.8.0_linux_${SHOW_ME_ARCH}.zip ];then unzip -qq -o -d /usr/local/bin /opt/show-me/packer_1.8.0_linux_${SHOW_ME_ARCH}.zip;fi
  - cp -a /opt/show-me/maas/aws/helpers/usr/local/bin/petname-helper.sh /usr/local/bin/
  - cp -a /opt/show-me/maas/aws/helpers/usr/local/bin/add-clients.sh /usr/local/bin/
  - cp -a /opt/show-me/maas/aws/helpers/etc/systemd/system/show-me-files.service /etc/systemd/system/
  - cp -a /opt/show-me/maas/aws/helpers/home/ubuntu/.ssh/id_rsa /home/ubuntu/.ssh/
  - cp -a /opt/show-me/maas/aws/helpers/home/ubuntu/.ssh/id_rsa.pub /home/ubuntu/.ssh/
  - cp -a /opt/show-me/maas/aws/helpers/home/ubuntu/maas.lynx /home/ubuntu/
  - cp -a /opt/show-me/maas/aws/helpers/usr/local/bin/aws_show-me_maas_lxd-preseed.sh /usr/local/bin/
  - cp -a /opt/show-me/maas/aws/helpers/etc/ssl/certs/show-me_host.pem /etc/ssl/certs/
  - cp -a /opt/show-me/maas/aws/helpers/etc/ssl/private/show-me_host.key /etc/ssl/private/
  - cp -a /opt/show-me/maas/aws/helpers/etc/ssl/certs/show-me_ca.crt /etc/ssl/certs/
  - chown -R "root:root" /usr/local/bin/ /etc/ssl /etc/systemd/system/
  - chmod -R 0755 /usr/local/bin/
  - chown "$(id -un 1000):$(id -un 1000)" /home/$(id -un 1000)/
  - chmod 0400 /home/ubuntu/.ssh/id_rsa
  - chmod 0640 /home/ubuntu/.ssh/id_rsa.pub /home/ubuntu/maas.lynx
  - cp -a /etc/ssl/certs/show-me_ca.crt /usr/local/share/ca-certificates/
  - update-ca-certificates --fresh --verbose
  - if $(test -n "$(command 2>/dev/null -v lxd.lxc)");then su - $(id -un 1000) -c 'sudo snap refresh lxd --channel latest/stable';else su - $(id -un 1000) -c 'sudo snap install lxd';fi
  - snap restart snapd
  - for GROUP in docker kvm libvirt libvirt-qemu lxd landscape;do if [ "$(getent group $GROUP;echo $?)" = "0" ];then usermod -a -G $GROUP $(id -un 1000);fi;done
  - if ! $(grep -qE 'PATH.*/snap/bin' /etc/environment);then sed -i -r '1s|\x22$|\x3a/snap/bin&|g' /etc/environment;fi
  - echo "EDITOR=/usr/bin/vim.basic"|tee 1>/dev/null -a /etc/environment
  - . /etc/environment
  - if [ -f /usr/local/bin/petname-helper.sh ];then /usr/local/bin/petname-helper.sh;fi
  - if [ -f /etc/systemd/system/show-me-files.service ];then systemctl daemon-reload;for S in enable start start status;do systemctl $S show-me-files.service;sleep .5;done;fi
  - if [ -f /etc/ssl/certs/show-me_ca.crt ];then ln -sf /etc/ssl/certs/show-me_ca.crt /etc/show-me/www/;fi
  - if [ -f /etc/ssl/certs/show-me_host.pem ];then ln -sf /etc/ssl/certs/show-me_host.pem /etc/show-me/www/;fi
  - export PG_DBVER=$(psql -V|awk '{gsub(/\..*$/,"");print $3}')
  - export PG_DBHBA="/etc/postgresql/${PG_DBVER}/main/pg_hba.conf"
  - export PG_DBVER=$(psql -V|awk '{gsub(/\..*$/,"");print $3}')
  - export PG_DBHBA="/etc/postgresql/${PG_DBVER}/main/pg_hba.conf"
  - export PG_DBHOST='maas.ubuntu-show.me' PG_DBUSER=postgres PG_DBNAME=postgres PG_DBPORT=5432
  - export PG_DBSSL_CRT=/etc/ssl/certs/show-me_ca.crt
  - export PG_DBSSL_PEM=/etc/ssl/certs/show-me_host.pem
  - export PG_DBSSL_KEY=/etc/ssl/private/show-me_host.key
  - su - postgres -c "psql postgres -c \"ALTER SYSTEM SET ssl to 'on';\""
  - su - postgres -c "psql postgres -c \"ALTER SYSTEM SET ssl_ca_file to '${PG_DBSSL_CRT}';\""
  - su - postgres -c "psql postgres -c \"ALTER SYSTEM SET ssl_cert_file to '${PG_DBSSL_PEM}';\""
  - su - postgres -c "psql postgres -c \"ALTER SYSTEM SET ssl_key_file to '${PG_DBSSL_KEY}';\""
  - su - postgres -c "psql postgres -c \"ALTER SYSTEM SET listen_addresses to '*';\""
  - su - postgres -c "psql postgres -c \"ALTER SYSTEM SET max_connections to '500';\""
  - su - postgres -c "psql postgres -c \"ALTER SYSTEM SET max_prepared_transactions to '500';\""
  - su - postgres -c 'psql -P pager=off  postgres -xtc "select name,setting from pg_settings where name SIMILAR TO '"'"'listen%|max%(con|prep)%|ssl|ssl_(ca|cert|key)%'"'"';"'
  - export LANDSCAPE_DBVER=$(psql -V|awk '{gsub(/\..*$/,"");print $3}')
  - export LANDSCAPE_DBHBA="/etc/postgresql/${LANDSCAPE_DBVER}/main/pg_hba.conf"
  - export LANDSCAPE_DBHOST='maas.ubuntu-show.me' LANDSCAPE_DBUSER=landscape LANDSCAPE_DBNAME='landscapedb' LANDSCAPE_DBPORT=5432
  - export LANDSCAPE_DBPASS="$(env LANG=C LC_ALL=C tr 2>/dev/null -dc "[:alnum:]" < /dev/urandom|fold -w12|head -n1)"
  - export LANDSCAPE_DBCON="postgres://${LANDSCAPE_DBUSER}:${LANDSCAPE_DBPASS}@${LANDSCAPE_DBHOST}:${LANDSCAPE_DBPORT}/${LANDSCAPE_DBNAME}"
  - su - postgres -c 'psql -c "CREATE ROLE '${LANDSCAPE_DBUSER}' WITH SUPERUSER CREATEDB CREATEROLE LOGIN REPLICATION ENCRYPTED PASSWORD '"'"''${LANDSCAPE_DBPASS}''"'"';"'
  - su - postgres -c 'psql -c "CREATE DATABASE '${LANDSCAPE_DBNAME}' WITH OWNER '"'"''${LANDSCAPE_DBUSER}''"'"';"'
  - echo "${LANDSCAPE_DBHOST}:${LANDSCAPE_DBPORT}:${LANDSCAPE_DBNAME}:${LANDSCAPE_DBUSER}:${LANDSCAPE_DBPASS}"|su postgres -c 'tee 1>/dev/null /var/lib/postgresql/.pgpass.landscape'
  - printf '%-08s%-016s%-016s%-024s%s\n' host ${LANDSCAPE_DBNAME} ${LANDSCAPE_DBUSER} '::/0' md5 host ${LANDSCAPE_DBNAME} ${LANDSCAPE_DBUSER} '0.0.0.0/0' md5|su - postgres -c 'tee -a '${LANDSCAPE_DBHBA}''
  - export SSP_DBVER=$(psql -V|awk '{gsub(/\..*$/,"");print $3}')
  - export SSP_DBHBA="/etc/postgresql/${SSP_DBVER}/main/pg_hba.conf"
  - export SSP_DBHOST=maas.ubuntu-show.me SSP_DBUSER=snap-proxy SSP_DBNAME='snap-proxy-db' SSP_DBPORT=5432
  - export SSP_DBPASS="$(env LANG=C LC_ALL=C tr 2>/dev/null -dc "[:alnum:]" < /dev/urandom|fold -w12|head -n1)"
  - export SSP_DBCON="postgres://${SSP_DBUSER}:${SSP_DBPASS}@${SSP_DBHOST}:${SSP_DBPORT}/${SSP_DBNAME}"
  - |-
    cat <<-SQL|su - postgres -c psql
    CREATE ROLE "${SSP_DBUSER}" LOGIN CREATEROLE PASSWORD '${SSP_DBPASS}';
    CREATE DATABASE "${SSP_DBNAME}" OWNER "${SSP_DBUSER}";
    \connect "${SSP_DBNAME}"
    CREATE EXTENSION "btree_gist";
    SQL
  - echo "${SSP_DBHOST}:${SSP_DBPORT}:${SSP_DBNAME}:${SSP_DBUSER}:${SSP_DBPASS}"|su postgres -c 'tee 1>/dev/null /var/lib/postgresql/.pgpass.ssp'
  - printf '%-08s%-016s%-016s%-024s%s\n' host ${SSP_DBNAME} ${SSP_DBUSER} '::/0' md5 host ${SSP_DBNAME} ${SSP_DBUSER} '0.0.0.0/0' md5|su - postgres -c 'tee -a '${SSP_DBHBA}''
  - export CANDID_DBVER=$(psql -V|awk '{gsub(/\..*$/,"");print $3}')
  - export CANDID_DBHBA="/etc/postgresql/${CANDID_DBVER}/main/pg_hba.conf"
  - export CANDID_DBHOST='maas.ubuntu-show.me' CANDID_DBUSER=candid CANDID_DBNAME='candiddb' CANDID_DBPORT=5432
  - export CANDID_DBPASS="$(env LANG=C LC_ALL=C tr 2>/dev/null -dc "[:alnum:]" < /dev/urandom|fold -w12|head -n1)"
  - export CANDID_DBCON="postgres://${CANDID_DBUSER}:${CANDID_DBPASS}@${CANDID_DBHOST}:${CANDID_DBPORT}/${CANDID_DBNAME}"
  - su - postgres -c 'psql -c "CREATE ROLE '${CANDID_DBUSER}' WITH SUPERUSER CREATEDB CREATEROLE LOGIN REPLICATION ENCRYPTED PASSWORD '"'"''${CANDID_DBPASS}''"'"';"'
  - su - postgres -c 'psql -c "CREATE DATABASE '${CANDID_DBNAME}' WITH OWNER '"'"''${CANDID_DBUSER}''"'"';"'
  - echo "${CANDID_DBHOST}:${CANDID_DBPORT}:${CANDID_DBNAME}:${CANDID_DBUSER}:${CANDID_DBPASS}"|su postgres -c 'tee 1>/dev/null /var/lib/postgresql/.pgpass.candid'
  - printf '%-08s%-016s%-016s%-024s%s\n' host ${CANDID_DBNAME} ${CANDID_DBUSER} '::/0' md5 host ${CANDID_DBNAME} ${CANDID_DBUSER} '0.0.0.0/0' md5|su - postgres -c 'tee -a '${CANDID_DBHBA}''
  - export RBAC_DBVER=$(psql -V|awk '{gsub(/\..*$/,"");print $3}')
  - export RBAC_DBHBA="/etc/postgresql/${RBAC_DBVER}/main/pg_hba.conf"
  - export RBAC_DBHOST='maas.ubuntu-show.me' RBAC_DBUSER=rbac RBAC_DBNAME='rbacdb' RBAC_DBPORT=5432
  - export RBAC_DBPASS="$(env LANG=C LC_ALL=C tr 2>/dev/null -dc "[:alnum:]" < /dev/urandom|fold -w12|head -n1)"
  - export RBAC_DBCON="postgres://${RBAC_DBUSER}:${RBAC_DBPASS}@${RBAC_DBHOST}:${RBAC_DBPORT}/${RBAC_DBNAME}"
  - su - postgres -c 'psql -c "CREATE ROLE '${RBAC_DBUSER}' WITH SUPERUSER CREATEDB CREATEROLE LOGIN REPLICATION ENCRYPTED PASSWORD '"'"''${RBAC_DBPASS}''"'"';"'
  - su - postgres -c 'psql -c "CREATE DATABASE '${RBAC_DBNAME}' WITH OWNER '"'"''${RBAC_DBUSER}''"'"';"'
  - echo "${RBAC_DBHOST}:${RBAC_DBPORT}:${RBAC_DBNAME}:${RBAC_DBUSER}:${RBAC_DBPASS}"|su postgres -c 'tee 1>/dev/null /var/lib/postgresql/.pgpass.rbac'
  - printf '%-08s%-016s%-016s%-024s%s\n' host ${RBAC_DBNAME} ${RBAC_DBUSER} '::/0' md5 host ${RBAC_DBNAME} ${RBAC_DBUSER} '0.0.0.0/0' md5|su - postgres -c 'tee -a '${RBAC_DBHBA}''
  - export MAAS_DBVER=$(psql -V|awk '{gsub(/\..*$/,"");print $3}')
  - export MAAS_PROFILE="maas-admin" MAAS_PASSWORD="ubuntu" MAAS_URIPORT=5240
  - export MAAS_FQDN='maas.ubuntu-show.me' MAAS_EMAIL='maas-admin@ubuntu-show.me' MAAS_IMPORTID='lp:craig-bender'
  - export MAAS_DBVER=$(psql -V|awk '{gsub(/\..*$/,"");print $3}')
  - export MAAS_DBHBA="/etc/postgresql/${MAAS_DBVER}/main/pg_hba.conf"
  - export MAAS_DBHOST='maas.ubuntu-show.me' MAAS_DBUSER=maas MAAS_DBNAME='maasdb' MAAS_DBPORT=5432
  - export MAAS_DBPASS="$(env LANG=C LC_ALL=C tr 2>/dev/null -dc "[:alnum:]" < /dev/urandom|fold -w12|head -n1)"
  - export MAAS_DBCON="postgres://${MAAS_DBUSER}:${MAAS_DBPASS}@${MAAS_DBHOST}:${MAAS_DBPORT}/${MAAS_DBNAME}"
  - export MAAS_URL="http://${MAAS_FQDN}:${MAAS_URIPORT}/MAAS"
  - su - postgres -c 'psql -c "CREATE ROLE '${MAAS_DBUSER}' WITH SUPERUSER CREATEDB CREATEROLE LOGIN REPLICATION ENCRYPTED PASSWORD '"'"''${MAAS_DBPASS}''"'"';"'
  - su - postgres -c 'psql -c "CREATE DATABASE '${MAAS_DBNAME}' WITH OWNER '"'"''${MAAS_DBUSER}''"'"';"'
  - echo "${MAAS_DBHOST}:${MAAS_DBPORT}:${MAAS_DBNAME}:${MAAS_DBUSER}:${MAAS_DBPASS}"|su postgres -c 'tee 1>/dev/null /var/lib/postgresql/.pgpass.maas'
  - cp -a /var/lib/postgresql/.pgpass* /home/$(id -un 1000)/;chown -R "$(id -un 1000):$(id -un 1000)" /home/$(id -un 1000)/\.*
  - printf '%-08s%-016s%-016s%-024s%s\n' host ${MAAS_DBNAME} ${MAAS_DBUSER} '::/0' md5 host ${MAAS_DBNAME} ${MAAS_DBUSER} '0.0.0.0/0' md5|su - postgres -c 'tee -a '${MAAS_DBHBA}''
  - su - postgres -c 'psql postgres -c "SELECT pg_reload_conf();"'
  - for P in LANDSCAPE SSP RBAC CANDID MAAS PG SHOW_ME;do set|grep "^${P}_";done|sort -uV|tee ~/.show-me.rc|su - $(id -un 1000) -c 'tee ~/.show-me.rc'|su - postgres -c 'tee ~/.show-me.rc'
  - echo 'for RC in $(find ~/ -maxdepth 1 -type f -iname ".show-me*.rc");do source $RC;done'|tee -a /root/.bashrc |su - $(id -un 1000) -c 'tee -a ~/.bashrc'|su - postgres -c 'tee -a ~/.bashrc'
  - apt install maas -o Acquire::ForceIPv4=true -yqf --auto-remove --purge
  - maas init --force --mode=region --maas-url="${MAAS_URL}" --database-host=${MAAS_DBHOST} --database-name=${MAAS_DBNAME} --database-user=${MAAS_DBUSER} --database-pass=${MAAS_DBPASS} --database-port=${MAAS_DBPORT}
  - maas createadmin --username ${MAAS_PROFILE} --password ${MAAS_PASSWORD} --email ${MAAS_EMAIL} --ssh-import "${MAAS_IMPORTID}"
  - maas login ${MAAS_PROFILE} ${MAAS_URL} \$(sudo maas apikey --username=${MAAS_PROFILE})
  - su - $(id -un 1000) -c 'maas login '${MAAS_PROFILE}' '${MAAS_URL}' $(sudo maas apikey --username='${MAAS_PROFILE}')'  - if [ -f /etc/lynx/lynx.cfg ];then sed -i -r "s/^#?(FORCE_SSL_COOKIE.*:|SET_COOKIE.*:|ACCEPT_ALL_COOKIE.*:)[^$]*/\1TRUE/;s/^#?(COOKIE_LOOSE_INVALID_DOMAINS:)[^$]*/\1$(hostname -I|sed -r 's/\x20/\n/g'|sed -r '/:|^$/d;1s/^/'$(hostname -d)'\n/g'|paste -sd,)/;s/^#?(FORCE_COOKIE_PROMPT.*:|FORCE_SSL_PROMPT.*:)[^$]*/\1yes/;s/^#?(COOKIE_.*FILE:.*$)/\1/" /etc/lynx/lynx.cfg;fi
  #- if [ -f /home/$(id -un 1000)/maas.lynx ];then lynx -cmd_script=/home/$(id -un 1000)/maas.lynx https://$(hostname -f);fi
  - if [ -f /usr/local/bin/aws_show-me_maas_lxd-preseed.sh ];then /usr/local/bin/aws_show-me_maas_lxd-preseed.sh;fi
  - "lxc image copy ubuntu-daily:focal local: --copy-aliases --alias maas-controller-focal --auto-update --public"
  - "lxc remote add min https://cloud-images.ubuntu.com/minimal/daily --protocol simplestreams --accept-certificate"
  - "for I in $(lxc image list min: -cfl|awk '/more|CONTAIN/{print $4}'|sort -uV|sed '1h;1d;$!H;$!d;G');do ((lxc image copy min:${I} local: --alias maas-tgt-${I} --alias ${I}-min --auto-update --public) &);done"