#cloud-config
final_message: 'MAAS Show Me Demo Installed in $UPTIME'
merge_how:
 - name: list
   settings: [append]
 - name: dict
   settings: [no_replace, recurse_list]
manage_etc_hosts: false
preserve_hostname: true
prefer_fqdn_over_hostname: true
fqdn: maas.ubuntu-show.me
hostname: maas
locale: en_US.UTF-8
package_update: true
package_upgrade: true
packages: [amtterm, dnsutils, build-essential, debconf-utils, dialog, git, gnupg, jq, landscape-client, lynx, maas-cli, maas-common, postgresql-client, postgresql-common, postgresql, software-properties-common, ssl-cert, tree, unzip, vim, wsmancli]
apt:
  conf: |
    APT {
      Get {
        Assume-Yes "true";
        Fix-Broken "true";
        Auto-Remove "true";
        Purge "true";
      };
      Acquire {
        ForceIPv4 "true";
        Check-Date "false";
      };
    };
  primary:
    - arches: [amd64]
      uri: 'http://us.archive.ubuntu.com/ubuntu'
      search: ['http://us.archive.ubuntu.com/ubuntu', 'http://us.archive.ubuntu.com/ubuntu']
  security:
    - arches: [amd64]
      uri: 'http://us.archive.ubuntu.com/ubuntu'
      search: ['http://us.archive.ubuntu.com/ubuntu', 'http://us.archive.ubuntu.com/ubuntu']
  sources_list: |
    deb [arch=amd64] $PRIMARY $RELEASE main universe restricted multiverse
    deb [arch=amd64] $PRIMARY $RELEASE-updates main universe restricted multiverse
    deb [arch=amd64] $SECURITY $RELEASE-security main universe restricted multiverse
    deb [arch=amd64] $PRIMARY $RELEASE-backports main universe restricted multiverse
  #sources:
    #maas-ubuntu-3_1-focal.list:
    #  source: 'deb [arch=amd64] https://ppa.launchpadcontent.net/maas/3.1/ubuntu focal main'
    #  keyid: 3AB6DCF1F234E78DAA9C104204E7FDC5684D4A1C
bootcmd:
  - ['cloud-init-per', 'once', 'bc0', 'set', '-x']
#  - ['cloud-init-per', 'once', 'net0', 'echo', 'network: {config: disabled}', '>', '/etc/cloud/cloud.cfg.d/99-disable-network-config.cfg']
  - ['cloud-init-per', 'once', 'net1', 'sysctl', '-w', 'net.ipv4.ip_forward=1']  
  - if [ "$(readlink -f /etc/resolv.conf)" = "/run/resolvconf/resolv.conf" ];then ln -sf /run/systemd/resolve/resolv.conf /etc/resolv.conf;fi
  - ['cloud-init-per', 'once', 'net2', 'printf', '"%s\x20%s\x20\x20%s\n"', 'precedence', '::ffff:0:0/96', '100', '|', 'tee', '-a', '/etc/gai.conf']
  #- |-
  #  cat <<-NETPLAN|sed -r 's/[ \t]+$//g;/^$/d'|tee 1>/dev/null /etc/netplan/50-cloud-init.yaml
  #  network:
  #    version: 2
  #    renderer: networkd
  #    ethernets:
  #      ens5:
  #        dhcp4: false
  #        dhcp6: false
  #        optional: false
  #        accept-ra: false
  #        link-local: [ ]
  #        match:
  #          macaddress: '$(ip -o l show dev ens5|grep -oP "(?<=ether )[^ ]+")'
  #        set-name: ens5
  #    bridges:
  #      br0:
  #        macaddress: '$(ip -o l show dev ens5|grep -oP "(?<=ether )[^ ]+")'
  #        interfaces: ['ens5']
  #        link-local: [ ]
  #        dhcp4: true
  #        dhcp4-overrides:
  #          use-dns: false
  #          use-hostname: false
  #          use-domains: false
  #          route-metric: 1
  #        dhcp6: false
  #        optional: false
  #        accept-ra: false
  #        link-local: [ ]
  #        nameservers:
  #          addresses: [8.8.8.8,1.1.1.1]
  #          search: [ubuntu-show.me]
  #        parameters:
  #          priority: 1
  #          stp: false
  #  NETPLAN
  #- ['cloud-init-per', 'once', 'net3', 'netplan', '--debug', 'generate']
  #- ['cloud-init-per', 'once', 'net4', 'netplan', '--debug', 'apply']
  #- ['cloud-init-per', 'once', 'net5', 'netplan', '--debug', 'apply']
  - ['cloud-init-per', 'once', 'net6', 'systemctl', 'restart', 'systemd-networkd', 'systemd-resolved', 'procps.service']
  #- ['cloud-init-per', 'once', 'net7', 'ip', 'addr', 'flush', 'ens5']
  - ['cloud-init-per', 'once', 'apt1',  'DEBIAN_FRONTEND=noninteractive', 'apt-get', '--option=Acquire::ForceIPv4=true', 'update']
  - ['cloud-init-per', 'once', 'apt2',  'DEBIAN_FRONTEND=noninteractive', 'apt-get', 'dist-upgrade', '--option=Acquire::ForceIPv4=true', '--assume-yes', '--quiet', '--auto-remove', '--purge']
  - ['cloud-init-per', 'once', 'apt3',  'DEBIAN_FRONTEND=noninteractive', 'apt-get', 'install', 'dnsutils', 'debconf-utils', 'dialog', 'gnupg', '--option=Acquire::ForceIPv4=true', '--assume-yes', '--quiet', '--auto-remove', '--purge']
  - ['cloud-init-per', 'once', 'apt4',  'DEBIAN_FRONTEND=noninteractive', 'apt-get', 'remove', 'lxd', 'lxd-client', '--auto-remove', '--purge', '--assume-yes', '--quiet', '--fix-broken', '--option=Acquire::ForceIPv4=true']
runcmd:
  - set -x
  - export SHOW_ME_PNIC=ens5
  - export SHOW_ME_ARCH='amd64'
  - export SHOW_ME_APP='maas'
  - export SHOW_ME_SUBSTRT='aws'
  - export SHOW_ME_GIT="https://github.com/ThinGuy/show-me.git"
  - export DEBIAN_FRONTEND=noninteractive
  - "export PYTHONWARNINGS='ignore::DeprecationWarning'"
  - echo "export PYTHONWARNINGS='ignore::DeprecationWarning'"|tee -a 1>/dev/null /etc/environment
  - if [ -f /usr/bin/vim.basic ];then echo "export EDITOR='/usr/bin/vim.basic'"|tee -a 1>/dev/null /etc/environment;fi
  - export DEFAULT_IP="$(ip -o -4 a show $(ip -o r l default|grep ${SHOW_ME_PNIC}|grep -m1 -oP '(?<=dev )[^ ]+')|grep -m1 -oP '(?<=inet )[^/]+')"
  - export PUBLIC_IP_LIST="$(printf '%s\n' $(dig +short myip.opendns.com @resolver1.opendns.com) $(dig TXT +short o-o.myaddr.l.google.com @ns1.google.com|sed -r 's/\x22//g') $(dig +short txt ch whoami.cloudflare @1.0.0.1|sed -r 's/\x22//g'))"
  - if [ $(echo "${PUBLIC_IP_LIST}"|uniq -D|wc -l) -eq 3 ];then export PUBLIC_IP=$(echo "${PUBLIC_IP_LIST}"|uniq -d);fi
  - if [ -n $DEFAULT_IP -o -n $PUBLIC_IP ];then sed -i -r "/127.0|$(hostname -s)/d" /etc/hosts;fi
  - if [ -n $DEFAULT_IP ];then sed -i -r "1s/^/127.0.0.1\tlocalhost\n${DEFAULT_IP}\t$(hostname -s).ubuntu-show.me $(hostname -s)\n/" /etc/hosts;fi
  - if [ -n $PUBLIC_IP ];then sed -r -i "/$(hostname -s)$/a $PUBLIC_IP\t$(hostname -s).ubuntu-show.me $(hostname -s)\n/";fi
  - systemctl restart systemd-networkd systemd-resolved procps.service
  - for i in SHOW_ME_PNIC SHOW_ME_ARCH SHOW_ME_APP SHOW_ME_SUBSTRT SHOW_ME_GIT EDITOR PYTHONWARNINGS PUBLIC_IP DEFAULT_IP;do if [ -n "$(eval echo -n \"\$${i}\")" ];then printf "export ${i}=\"$(eval echo -n \$$i)\"\n";fi;done|tee -a 1>/dev/null /etc/environment
  - . /etc/environment
  - sleep 6
  - apt update -o "Acquire::ForceIPv4=true"
  - mkdir -p /etc/show-me/www /etc/show-me/log
  - if [ -d /opt/show-me ];then rm -rf /opt/show-me;fi
  - ping -c10 -w1 github.com
  - sleep 10
  - git clone https://github.com/ThinGuy/show-me.git /opt/show-me
  - git clone https://github.com/canonical/packer-maas /opt/show-me/packer-maas
  - curl -fSlL -o /opt/show-me/packer_1.8.0_linux_amd64.zip "https://releases.hashicorp.com/packer/1.8.0/packer_1.8.0_linux_${SHOW_ME_ARCH}.zip"
  - if [ -f /opt/show-me/packer_1.8.0_linux_${SHOW_ME_ARCH}.zip ];then unzip -qq -o -d /usr/local/bin /opt/show-me/packer_1.8.0_linux_${SHOW_ME_ARCH}.zip;fi
  - install -o 0 -g 0 -m 0754 /opt/show-me/all/helpers/petname-helper.sh /usr/local/bin/petname-helper.sh
  - install -o 0 -g 0 -m 0754 /opt/show-me/all/helpers/petname-helper.sh /usr/local/bin/petname-helper.sh
  - install -o 0 -g 0 -m 0400 /opt/show-me/all/pki/ubuntu-show-me-id_rsa /home/$(id -un 1000)/.ssh/showme_rsa
  - install -o 0 -g 0 -m 0640 /opt/show-me/all/pki/ubuntu-show-me-id_rsa.pub /home/$(id -un 1000)/.ssh/showme_rsa.pub
  - install -o 0 -g 0 -m 0644 /opt/show-me/all/pki/ubuntu-show-me-id_rsa.pub /home/$(id -un 1000)/.ssh/authorized_keys
  - install -o 0 -g 0 -m 0755 -d /usr/local/lib/show-me/petname2/
  - install -o 0 -g 0 -m 0754 /opt/show-me/all/helpers/show-me_maas_lxd-init.sh /usr/local/bin/show-me_maas_lxd-init.sh
  - install -o 0 -g 0 -m 0754 /opt/show-me/all/helpers/show-me_postgresql-init.sh /usr/local/bin/show-me_postgresql-init.sh
  - install -o 0 -g 0 -m 0644 /opt/show-me/all/pki/show-me_host.crt /etc/ssl/certs/show-me_host.crt
  - install -o 0 -g 0 -m 0600 /opt/show-me/all/pki/show-me_host.key /etc/ssl/private/show-me_host.key
  - install -o 0 -g 0 -m 0644 /opt/show-me/all/pki/show-me_ca.crt /etc/ssl/certs/show-me_ca.crt
  - install -o 0 -g 0 -m 0644 /opt/show-me/all/pki/show-me_ca.crt /etc/ssl/certs/maas_ca.crt
  - install -o 0 -g 0 -m 0644 /opt/show-me/all/pki/show-me_host.crt /etc/ssl/certs/maas_host.crt
  - install -o 0 -g 0 -m 0600 /opt/show-me/all/pki/show-me_host.key /etc/ssl/private/maas_host.key
  - install -o 0 -g 0 -m 0754 /opt/show-me/all/helpers/show-me_file-service_init.sh /usr/local/bin/show-me_file-service_init.sh
  - install -o 0 -g 0 -m 0754 /opt/show-me/all/helpers/show-me_finishing-script_all.sh /usr/local/bin/show-me_finishing-script_all.sh
  - if [ -f /etc/ssl/certs/show-me_ca.crt ];then cp -a /etc/ssl/certs/show-me_ca.crt /usr/local/share/ca-certificates/show-me_ca.crt;fi
  - if [ -f /etc/ssl/certs/show-me_host.crt ];then ln -sf /etc/ssl/certs/show-me_ca.crt /etc/show-me/www/.;fi
  - install -o 0 -g 0 -m 0644 /opt/show-me/all/pki/show-me_full-chain.pem /etc/ssl/certs/show-me_full-chain.pem
  - install -o 0 -g 0 -m 0644 /opt/show-me/all/pki/show-me_basic-chain.pem /etc/ssl/certs/show-me_basic-chain.pem
  - if [ -f /etc/ssl/certs/show-me_full-chain.pem ];then ln -sf /etc/ssl/certs/show-me_full-chain.pem /etc/show-me/www/.;fi
  - if [ -f /etc/ssl/certs/show-me_basic-chain.pem ];then /etc/ssl/certs/show-me_basic-chain.pem /etc/show-me/www/.;fi
  - update-ca-certificates --fresh --verbose
  - if [ -f /usr/local/bin/show-me_postgresql-init.sh ];then /usr/local/bin/show-me_postgresql-init.sh;fi
  #### END of Postgresql section
  #### Begin Main Show-me App Section
  - if [ -f /root/.show-me.rc ];then . /root/.show-me.rc;fi
  - |-
    cat <<SUDOERS|sed -r 's/[ \t]+$//g;/^$/d'|sudo tee 1>/dev/null /etc/sudoers.d/99-default-user
    Defaults	env_reset
    Defaults	env_keep+="CANDID_* DISPLAY EDITOR HOME LANDSCAPE_* LANG* MAAS_* PG_* PYTHONWARNINGS RBAC_* SHOW_ME* SSP_* XAUTHORITY XAUTHORIZATION *_IP *_PROXY *_proxy"
    Defaults	secure_path="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin:$HOME/.local/bin"
    $(id -un 1000)		ALL=(ALL) NOPASSWD:ALL
    SUDOERS
  # For Deb
  #- apt install maas -o Acquire::ForceIPv4=true -yqf --auto-remove --purge
  #- maas init --admin-username=${MAAS_PROFILE} --admin-password ${MAAS_PASSWORD} --admin-email=${MAAS_EMAIL} --admin-ssh-import=${MAAS_IMPORTID} --candid-agent-file="" --candid-domain="" --candid-admin-group="" --rbac-url="" --rbac-service-name=""
  #- /usr/bin/maas login ${MAAS_PROFILE} ${MAAS_URL} \$(sudo /usr/bin/maas apikey --username=${MAAS_PROFILE})
  #- su - $(id -un 1000) -c '/usr/bin/maas login '${MAAS_PROFILE}' '${MAAS_URL}' $(sudo /usr/bin/maas apikey --username='${MAAS_PROFILE}')'
  # For snap
  - snap install maas
  - /snap/bin/maas init --force --mode=region --maas-url="${MAAS_URL}" --database-host=${MAAS_DBHOST} --database-name=${MAAS_DBNAME} --database-user=${MAAS_DBUSER} --database-pass=${MAAS_DBPASS} --database-port=${MAAS_DBPORT}
  - /snap/bin/maas createadmin --username ${MAAS_PROFILE} --password ${MAAS_PASSWORD} --email ${MAAS_EMAIL} --ssh-import "${MAAS_IMPORTID}"
  - /snap/bin/maas login ${MAAS_PROFILE} ${MAAS_URL} $(/snap/bin/maas apikey --username=${MAAS_PROFILE})
  - su - $(id -un 1000) -c '/snap/bin/maas login '${MAAS_PROFILE}' '${MAAS_URL}' $(sudo /snap/bin/maas apikey --username='${MAAS_PROFILE}')'
  - if $(test -n "$(command 2>/dev/null -v lxd.lxc)");then su - $(id -un 1000) -c 'sudo snap refresh lxd --channel latest/stable';else su - $(id -un 1000) -c 'sudo snap install lxd';fi
  - if [ -f /usr/local/bin/show-me_maas_lxd-init.sh ];then /usr/local/bin/show-me_maas_lxd-init.sh;fi
  - if [ -f /usr/local/bin/show-me_file-service_init.sh ];then /usr/local/bin/show-me_file-service_init.sh;fi
  - if [ -f /usr/local/bin/show-me/show-me_finishing-script_all.sh ];then /usr/local/bin/show-me/show-me_finishing-script_all.sh;fi
